services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306

  adminer:
    image: adminer
    ports:
      - 3308:8080

  spip-mysql:
    image: php:8.1
    ports:
      - 3309:80
    volumes:
      - ./html:/var/www/html
    working_dir: /var/www/html
    entrypoint: [
        "bash",
        "-c",
        "apt update
        && apt install -y
        libcurl3-dev \
        libxml2-dev \
        libmemcached-dev \
        libz-dev \
        libpq-dev \
        libjpeg-dev \
        libpng-dev \
        libfreetype6-dev \
        libssl-dev \
        libwebp-dev \
        libxpm-dev \
        libmcrypt-dev \
        libonig-dev \
        libzip-dev \
        libsodium-dev \
        wget \
        zip \
        default-mysql-client \
        && docker-php-ext-configure gd \
        --prefix=/usr
        --with-jpeg \
        --with-webp \
        --with-xpm \
        --with-freetype \
        && docker-php-ext-install
        sodium \
        phar \
        curl \
        xml \
        gd \
        zip \
        mysqli \
        && wget https://get.spip.net/spip_loader.php 
        && mv spip_loader.php spip_loader.phar
        && php -r '$$phar = new Phar(\"spip_loader.phar\");$$phar->extractTo(\".\");'
        && mv index.php spip_loader.php
        && sed -i 's/index.php/spip_loader.php/g' spip_loader.php
        && php -S 0.0.0.0:80",
      ]
