version: '3.9'
services:
  db:
    image: mysql:${MYSQL_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
  pma:
    image: phpmyadmin:latest
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3308:80	
  spip:
    image: spip_dev
    container_name: cspip
    ports:
      - 3309:80
