services:
  db:
    image: mysql:${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306

  adminer:
    image: adminer
    ports:
      - 3308:8080

  spip-mysql:
    image: spip_dev
    ports:
      - 3309:80